//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace J3Price.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceMst
    {
        public int ServiceID { get; set; }
        public string ServiceName { get; set; }
        public string ServiceNickName { get; set; }
        public Nullable<int> RegionID { get; set; }
    }
}
