//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace J3Price.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class J3PriceEntities : DbContext
    {
        public J3PriceEntities()
            : base("name=J3PriceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Products> Products { get; set; }
        public DbSet<Quotes> Quotes { get; set; }
        public DbSet<RegionMst> RegionMst { get; set; }
        public DbSet<ServiceMst> ServiceMst { get; set; }
        public DbSet<SaleTypeMst> SaleTypeMst { get; set; }
    }
}
